src/Entity/PostArticle.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PostArticleRepository")
 */
class PostArticle
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="asserts.article.title_not_blank")
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     * @Gedmo\Slug(fields={"title"})
     */
    private $slug;

    /**
     * @ORM\Column(type="text", nullable=false)
     * @Assert\NotBlank(message="asserts.article.description_not_blank")
     * @Assert\Length(min="10", minMessage="asserts.article.description_length")
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $publish_date;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\PostCategory", inversedBy="articles")
     */
    private $category;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPublishDate(): ?\DateTimeInterface
    {
        return $this->publish_date;
    }

    public function setPublishDate(\DateTimeInterface $publish_date): self
    {
        $this->publish_date = $publish_date;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getUpdatedDate(): ?\DateTimeInterface
    {
        return $this->updated_date;
    }

    public function setUpdatedDate(\DateTimeInterface $updated_date): self
    {
        $this->updated_date = $updated_date;

        return $this;
    }

    public function getCategory(): ?PostCategory
    {
        return $this->category;
    }

    public function setCategory(?PostCategory $category): self
    {
        $this->category = $category;

        return $this;
    }
}

src/Form/PostArticleType.php
<?php

namespace App\Form;

use App\Entity\PostArticle;
use App\Entity\PostCategory;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PostArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', null, [
                'label' => 'post.crud.form.title'
            ])
            ->add('description', null, [
                    'label' => 'post.crud.form.description'
            ])
            ->add('image', null, [
                'label' => 'post.crud.form.image'
            ])
            ->add('category', EntityType::class, [
                'class' => PostCategory::class,
                'label' => 'post.crud.form.category'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => PostArticle::class,
        ]);
    }
}

src/Controller/PostArticleController.php
<?php

namespace App\Controller;

use App\Entity\PostArticle;
use App\Form\PostArticleType;
use App\Repository\PostArticleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;

/**
 * @Route("/article")
 */
class PostArticleController extends AbstractController
{
    /**
     * @Route("/crud-list", name="post_article_index", methods={"GET"})
     * @param PostArticleRepository $postArticleRepository
     * @return Response
     */
    public function index(PostArticleRepository $postArticleRepository): Response
    {
        return $this->render('post_article/index.html.twig', [
            'post_articles' => $postArticleRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="post_article_new", methods={"GET","POST"})
     * @param Request $request
     * @return Response
     */
    public function new(Request $request): Response
    {
        $postArticle = new PostArticle();
        $form = $this->createForm(PostArticleType::class, $postArticle);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($postArticle);
            $entityManager->flush();

            return $this->redirectToRoute('post_article_index');
        }

        return $this->render('post_article/new.html.twig', [
            'post_article' => $postArticle,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{slug}", name="post_article_show", methods={"GET"})
     * @param PostArticle $postArticle
     * @return Response
     */
    public function show(PostArticle $postArticle): Response
    {
        $url = $this->generateUrl('post_article_show', [
            'slug' => $postArticle->getSlug()
        ], UrlGeneratorInterface::ABSOLUTE_URL);

        $twitter_params =
            '?text=' . urlencode($postArticle->getTitle()) . '+-' .
            '&amp;url=' . urlencode($url);

        $share_link = "http://twitter.com/share" . $twitter_params . "";
        return $this->render('post_article/show.html.twig', [
            'post_article' => $postArticle,
            'share_link' => $share_link
        ]);
    }

    /**
     * @Route("/{id}/edit", name="post_article_edit", methods={"GET","POST"})
     * @param Request $request
     * @param PostArticle $postArticle
     * @return Response
     */
    public function edit(Request $request, PostArticle $postArticle): Response
    {
        $form = $this->createForm(PostArticleType::class, $postArticle);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('post_article_index');
        }

        return $this->render('post_article/edit.html.twig', [
            'post_article' => $postArticle,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="post_article_delete", methods={"DELETE"})
     * @param Request $request
     * @param PostArticle $postArticle
     * @return Response
     */
    public function delete(Request $request, PostArticle $postArticle): Response
    {
        if ($this->isCsrfTokenValid('delete'.$postArticle->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($postArticle);
            $entityManager->flush();
        }

        return $this->redirectToRoute('post_article_index');
    }

    /**
     * @Route("/ajax/{offset}/{category_id}", name="post_article_fetch_array")
     * @param PostArticleRepository $articleRepository
     * @param $offset
     * @param null $category_id
     * @return Response
     */
    public function fetchAjax(PostArticleRepository $articleRepository, $offset = 0, $category_id = null)
    {
        $articles = $articleRepository->offsetLimitFind($offset, 10, $category_id);

        if (!$articles) {
            throw $this->createNotFoundException();
        }
        return $this->render('post_article/post_list.html.twig', [
            'articles' => $articles
        ]);
    }
}

templates/post_article/_delete_form.html.twig
<form method="post" action="{{ path('post_article_delete', {'id': post_article.id}) }}" onsubmit="return confirm('{{ "post.crud.delete_dialog" | trans }}');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ post_article.id) }}">
    <button class="btn btn-danger btn-block">{{ 'post.crud.delete_btn' | trans }}</button>
</form>

templates/post_article/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <div class="btn-group">
        <button class="btn btn-primary">{{ 'post.crud.save_btn' | trans }}</button>
        <a class="btn btn-secondary" href="{{ path('post_article_index') }}">{{ 'post.crud.back_btn' | trans }}</a>
    </div>
{{ form_end(form) }}

templates/post_article/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'post.crud.edit.title' | trans({'{title}': post_article.title}) ~ parent() }}{% endblock %}

{% block body %}
    <div class="container mt-4">
        <div class="card">
            <div class="card-header">{{ 'post.crud.edit.title' | trans({'{title}': post_article.title}) }}</div>

            <div class="card-body">
                {{ include('post_article/_form.html.twig') }}
            </div>

            <div class="card-footer">
                {{ include('post_article/_delete_form.html.twig') }}
            </div>
        </div>
    </div>
{% endblock %}

templates/post_article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'post.crud.index.title' | trans ~ parent() }}{% endblock %}

{% block body %}
    <div class="container mt-4">
        <div class="card">
            <div class="card-header">{{ 'post.crud.index.title' | trans }}</div>

            <table class="table">
                <thead>
                <tr>
                    <th>{{ 'post.crud.index.table.id' | trans }}</th>
                    <th>{{ 'post.crud.index.table.title' | trans }}</th>
                    <th>{{ 'post.crud.index.table.description' | trans }}</th>
                    <th>{{ 'post.crud.index.table.publish_date' | trans }}</th>
                    <th>{{ 'post.crud.index.table.actions' | trans }}</th>
                </tr>
                </thead>
                <tbody>
                {% for post_article in post_articles %}
                    <tr>
                        <td>{{ post_article.id }}</td>
                        <td>{{ post_article.title }}</td>
                        <td>{{ post_article.description }}</td>
                        <td>{{ post_article.publishDate ? post_article.publishDate|date('Y-m-d H:i:s') : '' }}</td>
                        <td>
                            <div class="btn-group-vertical btn-group-sm">
                                <a class="btn btn-secondary" href="{{ path('post_article_show', {'slug': post_article.slug}) }}">{{ 'post.crud.index.table.show' | trans }}</a>
                                <a class="btn btn-info" href="{{ path('post_article_edit', {'id': post_article.id}) }}">{{ 'post.crud.index.table.edit' | trans }}</a>
                            </div>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="5">{{ 'post.crud.index.table.no_records' | trans }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

            <div class="card-footer">
            </div>
        </div>
    </div>

    <div class="container position-fixed m-auto" style="bottom: 0; left: 0; right: 0;">
        <a href="{{ path('post_article_new') }}" class="btn btn-primary btn-block">{{ 'post.crud.index.add_btn' | trans }}</a>
    </div>
{% endblock %}

templates/post_article/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'post.crud.new.title' | trans ~ parent() }}{% endblock %}

{% block body %}
    <div class="container mt-4">
        <div class="card">
            <div class="card-header">{{ 'post.crud.new.title' | trans }}</div>

            <div class="card-body">
                {{ include('post_article/_form.html.twig') }}
            </div>
        </div>
    </div>
{% endblock %}

templates/post_article/post_list.html.twig
{% for article in articles %}
    <div class="grid-item col-4 d-none">
        <div class="card mb-4">
            {% if article.image is not empty %}
                <img src="{{ article.image }}" class="card-img-top" alt="{{ article.title }}">
            {% endif %}
            <div class="card-body">
                <h5 class="card-title"><span class="badge badge-{{ article.category_color }}">{{ article.category_name }}</span> {{ article.title }} <small class="text-muted">{{ article.publish_date | ago }}</small></h5>
                <div class="card-text">
                    {{ article.description | truncate(60, true, '...') }}
                </div>
                <a href="{{ path('post_article_show', {'slug': article.slug }) }}" class="btn btn-primary stretched-link">{{ 'post.btn.more' | trans }}</a>
            </div>
        </div>
    </div>
{% endfor %}

templates/post_article/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ post_article.title ~ parent() }}{% endblock %}

{% block body %}
    <div class="container mt-4">
        <div class="jumbotron pb-4 pt-4">
            <h3><span class="badge badge-{{ post_article.category.color }}">{{ post_article.category.name }}</span> {{ post_article.title }}</h3>
            <p class="text-muted font-italic mb-0">{{ 'post.publish_at' | trans }} {{ post_article.publishDate | ago }}<button onclick="window.open('{{ share_link }}','{{ "post.twitter_share" | trans }}','width=600,height=300')" class="btn btn-info float-right">{{ 'post.twitter_share' | trans }}</button></p>
        </div>

        <div>{{ post_article.description }}</div>
    </div>
{% endblock %}